// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Crud.Domain.Entities
{
    public partial class Genero
    {
        public Genero()
        {
            PeliculasGeneros = new HashSet<PeliculasGenero>();
        }

        public int IdGenero { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection<PeliculasGenero> PeliculasGeneros { get; set; }
    }
}