// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Crud.Domain.Entities
{
    public partial class Pelicula
    {
        public Pelicula()
        {
            Actuaciones = new HashSet<Actuacione>();
            PeliculasGeneros = new HashSet<PeliculasGenero>();
            Rankings = new HashSet<Ranking>();
        }

        public int IdPelicula { get; set; }
        public string Titulo { get; set; }
        public int AñoEstreno { get; set; }
        public string Clasificacion { get; set; }
        public int? IdProductora { get; set; }
        public int? IdDirector { get; set; }
        public decimal? Recaudacion { get; set; }

        public virtual Directore IdDirectorNavigation { get; set; }
        public virtual Productora IdProductoraNavigation { get; set; }
        public virtual ICollection<Actuacione> Actuaciones { get; set; }
        public virtual ICollection<PeliculasGenero> PeliculasGeneros { get; set; }
        public virtual ICollection<Ranking> Rankings { get; set; }
    }
}